# Site settings
title: 50 Days of Camino
subtitle: Kevin Soltysiak's travel log of the way of St. James, the "Camino de Santiago"
email: camino2016@ksol.fr
description: ""
baseurl: ""
url: "http://camino2016.ksol.fr"
twitter_username: "ksol"
github_username:  "ksol"
instagram_username: "ksol"

defaults:
  - scope:
      path: ""
    values:
      image: "https://s3.eu-central-1.amazonaws.com/camino2016/pictures/16/mountains-1-thumb.jpg"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
future: true
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag]

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
